### ISSUE TITLE
Downloadable files from within pub generate filenames with long strings of numbers.

### ISSUE THREAD

**Issue by aimeediehl** [pubpub/pubpub#2074] opened 2022-06-17 19:37 UTC
We've embedded three file downloads within one of our pubs, which is a collection of templates and a required form. The pub isn't yet published and is still in draft form. There are two Word templates for authors to use for submissions, and one fillable PDF form. (We're not using the submissions tool right now since we're just beginning to test our workflow.)

### What went wrong, step-by-step?
1. When clicked for download, the files download as requested but with random numbers for names, rather than the names we've given them.
2. Each file was downloaded individually and the same thing happened to each one.
...

### What did you expect to happen?
We expected each downloaded file to be named as it was on the site, such as "JEED Research Paper Template" or "JEED Author Agreement" rather than a random filename that has no meaning.

### What URL can we use to see the issue?
https://jeed.pubpub.org/pub/templates-and-forms/draft

### What browser/operating system were you using?
Firefox 101.0 on a MacBook Pro running MasOS Monterey version 12.4

===

### Have any screenshots? (Attach them by dragging the image here)
No screenshots but you can try it yourself at the link: https://jeed.pubpub.org/pub/templates-and-forms/draft

(Link will be published on Tuesday, June 21)

### Who reported this? (If not you)
I noticed it initially, other editors reviewing the content experienced the same thing. Thanks for your help!

**Comment by avanouse** [comment] 2022-06-27 11:45
I had issues opening a PubPub-generated Word doc today. Could this have something to do with the filename?

Word says:
<img width="261" alt="Screen Shot 2022-06-27 at 1 40 11 PM" src="https://user-images.githubusercontent.com/60357197/175933870-112b1e5b-4798-49cd-ad59-99390d2ea7bd.png">
Then:
<img width="263" alt="Screen Shot 2022-06-27 at 1 41 23 PM" src="https://user-images.githubusercontent.com/60357197/175933893-b0fb3208-456c-49fe-b2e6-808fef174b13.png">

**Comment by gabestein** [comment] 2022-06-27 13:02
Hi Allison — no, this isn't related to filenames. We had a bug for a few days that produced some bad word exports that this is probably related to. Try making a change to the draft and re-exporting the word doc. If that doesn't work, please file another bug for it and we'll take a look.

**Comment by gabestein** [comment] 2022-06-27 13:28
Hi Aimee — thanks, this is likely related to an upgrade we made to some underlying systems, so I've created a new issue for it. We're still discussing the file naming issue and do not have a timeline for it yet.

**Comment by idreyn** [comment] 2022-06-29 19:15
Quick note that the download icon is now visible again.

**Comment by howebenhowe** [comment] 2022-11-08 00:29
I _think_ this is a result of single-origin policy preventing the `download` attribute on `<a>` tags from having the desired effect.
Two solutions I've encountered so far:
+ proxying requests so that the server asks for the assets from our s3 bucket instead of the client
+ set up CORS on our bucket to permit access from pubpub.org (+ dev environments, staging apps on heroku...?)

**Comment by gabestein** [comment] 2023-02-07 01:54
Dupe of #519

**Closed by gabestein** 2023-02-07 01:54 UTC
Labels: bug
