### ISSUE TITLE
Clicking either link icon fails to pop up link textbox

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#695] opened 2020-02-04 16:14 UTC
As an editor on a doc,
On Win/Chrome or Mac/Chrome,
On 3 different docs so far (each longer than a few pages, possibly w/ multi cursor),
I select some text, click on the nearest link icon, no textbox pops up.   
I click on the link icon in the upper nav, no textbox pops up.  
I click again on the upper-nav icon, and it pops up.  

(also happened when clicking first on the upper nav icon; then the lower; then the upper)

**What URL can we use to see the issue?**
https://notes.knowledgefutures.org/pub/pdjc05p0/branch/2?access=qo2rkxb1

Part of a series of bugs around this workflow (see also #605, #693)

**Comment by gabestein** [comment] 2021-04-28 18:09
At least on the technical end, this is a duplicate of #605, even if it's a slightly different repro step.

**Closed by gabestein** 2021-04-28 18:09 UTC
Labels: bug
