### ISSUE TITLE
Recognizing two last names without a hyphen

### ISSUE THREAD

**Issue by sarah-tonin** [pubpub/pubpub#2096] opened 2022-06-27 13:46 UTC
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
The name  "Arianna Salazar Miranda" is cited as “A.S. Miranda” instead of “A. Salazar Miranda.”  

...

### What did you expect to happen?
Salazar Miranda should be considered the last name. 

### What URL can we use to see the issue?
https://projections.pubpub.org/dash/collection/16-measuring-the-city/settings

### What browser/operating system were you using?

===

**Comment by gabestein** [comment] 2022-06-27 13:58
Duplicate of https://github.com/pubpub/pubpub/issues/1063

**Closed by gabestein** 2022-06-27 13:58 UTC
Labels: bug
