### ISSUE TITLE
Tables of Contents now hard to see / generate

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#559] opened 2019-10-07 15:25 UTC
I tried to generate always-visible TOCs on long pubs without success. 

TOCs in the sidebar were welcome for long pubs.  Now there isn't an obvious way to render one, and finding the TOC resting behind one of the many unlabelled buttons at the top of a pub is not easy; also another 1-2 clicks to jump to the section heading you want.

A return to a way to do this, or documentation about indexes and TOCs, would be welcome.  (link to issues about longer chaptered works + optimal pub-length, too)

**Comment by gabestein** [comment] 2020-04-29 22:16
closing as a dupe of #761, which is more recent and active.

**Closed by gabestein** 2020-04-29 22:16 UTC
Labels: bug
