### ISSUE TITLE
URL spillover in some notes

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#1227] opened 2021-01-06 02:39 UTC
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

**What went wrong, step-by-step?**
1. Some urls are extending beyond their footnote boxes when you hover over them
2.
...

**What did you expect to happen?**

**What URL can we use to see the issue?**
http://recordit.co/Rr0tCj4H0d

**What browser/operating system were you using?**

---

**Have any screenshots? (Attach them by dragging the image here)**
https://recordit.co/Rr0tCj4H0d

**Who reported this? (If not you)**

**Comment by idreyn** [comment] 2021-02-25 20:17
Closed as duplicate of #1286 (which has a funnier title)

**Closed by idreyn** 2021-02-25 20:17 UTC
Labels: bug
