### ISSUE TITLE
I can't assign DOIs to individual pubs in this community-defined situation!

### ISSUE THREAD

**Issue by avanouse** [pubpub/pubpub#2350] opened 2022-11-15 12:22 UTC
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) intact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. I created a pub within a community that has community-level settings. I need to set a custom doi.
2. Navigated to the DOI tab in settings : there is a message that DOIs can be assigned to individual pubs by admins in this community (ie. not by me I assume)
3. discovered i am an admin in the community
...

### What did you expect to happen?
messages to be consistent with less permissions, or the opposite
(possibly I am just in the wrong place. if so, should a person in my position be directed to the right place?)

### What URL can we use to see the issue?
https://tmb.apaopen.org/dash/pub/xuyqf7l0/settings/doi

### What browser/operating system were you using?
chrome

===

### Have any screenshots? (Attach them by dragging the image here)
<img width="1063" alt="Screen Shot 2022-11-15 at 7 08 14 AM" src="https://user-images.githubusercontent.com/60357197/201916519-0e829eed-630f-44e6-b209-fb6f30ff4e14.png">

<img width="561" alt="Screen Shot 2022-11-15 at 7 09 43 AM" src="https://user-images.githubusercontent.com/60357197/201916586-209a83f5-09a6-4f41-944e-dd201069f496.png">

**Comment by gabestein** [comment] 2022-11-15 16:45
duplicate of #2343

**Closed by gabestein** 2022-11-15 16:45 UTC
Labels: bug
