### ISSUE TITLE
TOCs are awesome, now feel hidden

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#601] opened 2019-11-04 15:26 UTC
As a reader, I _loved_ the TOC in the sidebar for long documents.  Now it is hidden behind an opaque button, and I generally feel that TOCs are not available to me anymore (even when I remember how to pull one up), as opposed to feeling they are always there supporting my reading.

As a writer, I liked knowing whether or not a TOC was going to be displayed to readers when they first visited a page (and would love the ability to force the default to be "show TOC").

**Comment by gabestein** [comment] 2019-12-05 23:07
Duplicate of #559

**Closed by gabestein** 2019-12-05 23:07 UTC
Labels: enhancement, feature request

**Comment by metasj** [comment] 2019-12-10 00:05
[Unintended dup - I had a long list that I didn't file all at once in October, hadn't crossed this one off. ]
