### ISSUE TITLE
Header links

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#983] opened 2020-08-13 16:11 UTC
_Before filing your enhancement, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

**What's your enhancement request?**
Right now, headers that are also links don't appear underlined and there's no easy, visual way to know they're links. Can we change this?

**What would this enhancement help you accomplish?**
Relevant for an upcoming MITP book, Topology, that is publishing its ToC as text on a PubPub homepage and linking to pdfs of its chapters from each chapter title (this is temporary until we can import it into the platform). Has come up for other communities before but never so centrally. 

---

**Any attachments or reference images? (Drag them here)**

**What's the URL to your PubPub community?**
https://topology.pubpub.org/

**Who requested this? (If not you)***
CA + Topology authors

**Comment by gabestein** [comment] 2020-08-13 16:17
Duplicate of #818

**Closed by gabestein** 2020-08-13 16:17 UTC
Labels: enhancement
