### ISSUE TITLE
Loop video option

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#2500] opened 2023-02-06 17:59 UTC
### What's your enhancement request?

Add the option to loop videos to video media editor by adding loop HTML tag.

### What would this enhancement help you accomplish?

Allow looping for natively uploaded videos.

---

**Comment by howebenhowe** [comment] 2023-04-25 15:48
closing as duplicate of #2618

**Closed by howebenhowe** 2023-04-25 15:48 UTC
Labels: enhancement, 1-day, quick-wins
