### ISSUE TITLE
Do long urls go out of frame on hover for footnotes?

### ISSUE THREAD

**Issue by avanouse** [pubpub/pubpub#1051] opened 2020-09-27 19:41 UTC
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

**What went wrong, step-by-step?**
1. Hovered over a superscript fn numeral after adding the note text.
2. Looks like this:
<img width="723" alt="Screen Shot 2020-09-27 at 3 21 36 PM" src="https://user-images.githubusercontent.com/60357197/94373950-d4e96900-00d6-11eb-86e0-b7859fe8d20d.png">
...

**What did you expect to happen?**

**What URL can we use to see the issue?**https://wikipedia20.pubpub.org/pub/bk2j57tr/draft/55?from=21429&to=21438

**What browser/operating system were you using?**
chrome
---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**

**Comment by gabestein** [comment] 2021-03-19 20:26
Dupe of #1286, which has been resolved!

**Closed by gabestein** 2021-03-19 20:26 UTC
Labels: bug
