### ISSUE TITLE
Don't rewrite the URL when visiting the non-version-specific URL for a pub 

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#1492] opened 2021-06-25 22:26 UTC
As a pub author, or visitor from the web, when I land on a pub, or send someone to it via a link, I often want to see the latest public version. (e.g. https://notes.knowledgefutures.org/pub/data-sharing-questions vs https://notes.knowledgefutures.org/pub/data-sharing-questions/release/10)

The "cite" link on a pub generates this, but the URL in the browser bar redirects to the version-specific URL.  There is no URL that a) specifies "take me to the latest revision" and b) doesn't redirect to a specific version. This makes other workflows that use the URL, including some search engines, index / link to a specific version, regularly ending up out of date by the time they are used.  

I would like a redirect scheme that didn't rewrite the URL when loading the latest revision.

**Comment by gabestein** [comment] 2021-06-26 02:49
Duplicate of #993318.

We’ve discussed this decision at length, and still feel good about it.

**Closed by gabestein** 2021-06-26 02:49 UTC
Labels: feature request
