### ISSUE TITLE
Multi-cursor failing: user icon flickering for one user, and cursor being claimed

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#376] opened 2019-05-31 20:12 UTC
Observed: SJ + Travis

OS: Win + MacOS

While editing a private working draft, both of us would at times see one of the user-icons flicker in and out at the upper-right of the editing window.  One or both of us would have their cursor regularly claimed by the other's typing.  Refreshing, closing and reopening the page did not resolve this.  Logging out and back in may have (we stopped trying to trigger this while using the doc).

Hard to capture a screenshot, since it was the dynamic interaction that was the problem.

**Comment by gabestein** [comment] 2019-07-08 13:51
@isTravis @idreyn I know we've encountered this periodically...is it something that was addressed as part of the V6 memory leak/slowdown investgiations last week, or are we still on the hunt for the root cause?

**Comment by gabestein** [comment] 2019-08-05 21:11
We feel fairly confident that this was resolved in either some of the memory leak investigations done a few weeks ago, or as part of the changes in V6. So, we're provisionally closing it. Please re-open if you encounter this type of thing again.

**Closed by gabestein** 2019-08-05 21:11 UTC
Labels: bug
