### ISSUE TITLE
Author-Date and Author inline citation styles generate non-alphabetic, order-of-appearance-ordered citation lists

### ISSUE THREAD

**Issue by jeffpooley** [pubpub/pubpub#928] opened 2020-07-19 01:08 UTC
**What went wrong, step-by-step?**
1. I tested both the *author-date* and *author* inline citation styles on a Pub (as set in the Pub Settings)
2. The citations list generated in the footer Citations list was numbered, in the order that the citations appeared in the text—instead of first-author last-name alphabetical, in the mode of most (all?) author-based inline reference/citation lists. (The order-of-appareance principle of the numbered citation styles common in IEEE and ACM seems to have carried over to other inline citation formats that do not follow this principle.)
3. Since the author-date (e.g., (Goodall, 2015)) or author (e.g., (Goodall)) are the in-text anchors, the numbers generated in the footer Citations list have no in-text referents. The established convention, moreover, in most (all?) author-based inline reference/citation lists is alphabetic ordering.

...

**What did you expect to happen?**

I expected alphabetic ordering (based on first author last name), without numbering.

**What URL can we use to see the issue?**

https://www.mediastudies.press/pub/xapey9h4/release/1

**What browser/operating system were you using?**

Safari for iPadOS 14 beta

---

**Have any screenshots? (Attach them by dragging the image here)**

<img width="756" alt="citation1" src="https://user-images.githubusercontent.com/6372329/87864745-40c28f00-c93a-11ea-9c6c-ac0dd3e70e32.png">

<img width="833" alt="citations2" src="https://user-images.githubusercontent.com/6372329/87864744-34d6cd00-c93a-11ea-8323-13d86a369fe1.png">

**Comment by gabestein** [comment] 2021-03-19 20:32
Closing as a dupe of #1067 (even though this one was first), because it also has another suggestion. But agreed that we should adhere to conventions of the style selected (and, as a first step in that direction, move to the most common variant as suggested).

**Closed by gabestein** 2021-03-19 20:32 UTC
Labels: bug
