### ISSUE TITLE
[BUG] Publication date is not added to HTML <meta> tags

### ISSUE THREAD

**Issue by ThomasJorna** [pubpub/pubpub#948] opened 2020-07-27 14:26 UTC
**What's your enhancement request?**
I would like to have the publication date of the article added to the HTML <meta> tags in the header of Pubs. 
It could easily be done by simply including the tag:
`<meta name="citation_publication_date" content="2020/07/22">`  for instance.

More control over the meta tags would of course be amazing, but this simple addition would already help lots.

**What would this enhancement help you accomplish?**
Google Scholar requires this in order to parse the rest of the meta tags in the Pub-HTML, this would further increase our chances of having our Pubs indexed, as currently only the PDF is indexed by Scholar.
![image](https://user-images.githubusercontent.com/21983833/88553166-40ef1880-d025-11ea-8426-f0d730fab2d0.png)
Source: https://scholar.google.com/intl/en/scholar/inclusion.html#indexing

---

**Any attachments or reference images? (Drag them here)**
Absence of publication meta-tag.
![image](https://user-images.githubusercontent.com/21983833/88553354-78f65b80-d025-11ea-8f8a-54a0ce432204.png)

**What's the URL to your PubPub community?**
https://jtrialerror.pubpub.org

**Comment by ThomasJorna** [comment] 2020-07-28 10:49
Adding a publication date meta tag does seem to be intended, as seen for instance in the `server/utils/scrape.js`, so maybe it's more accurate to call this a bug.

![image](https://user-images.githubusercontent.com/21983833/88656517-bb28a700-d0d0-11ea-852f-15a4c0729dd5.png)

Source: https://github.com/pubpub/pubpub/blob/3545236808105b3a0ccefdd125d07b7d5b788513/server/utils/scrape.js

**Comment by gabestein** [comment] 2020-07-28 14:28
Hi, thanks for this! Indeed, it looks like a bug, as we used to include this tag, although the issue is a bit farther upstream. I've just pushed a fix for it (including adding a dc.date tag): #948.

**Closed** 2020-07-28 18:47 UTC
Labels: enhancement
