### ISSUE TITLE
Page not displaying correctly/not logging in 

### ISSUE THREAD

**Issue by mollygloom** [pubpub/pubpub#1199] opened 2020-12-15 16:17 UTC
**What went wrong, step-by-step?**
1. Unable to log in to SAR page, rejects email as invalid while signed into PubPub 
2. Pages do not display content correctly
...

**What did you expect to happen?**
To be able to access both public and admin sections of SAR.

**What URL can we use to see the issue?**

**What browser/operating system were you using?**
iPadOS 
---

**Have any screenshots? (Attach them by dragging the image here)**

**Who reported this? (If not you)**

**Comment by gabestein** [comment] 2020-12-15 17:21
Hi Molly – can you say more about what you experienced by providing a step-by-step description of exactly what you were trying to do?

In particular, I'm interested in this: `Pages do not display content correctly`

Did pages display incorrectly happen before you attempted to log in or after?

From your description, It seems like this may have been the result of the CSS and JavaScript not properly loading. Could you try refreshing the page a few times until the content looks correct, and then trying? Or, alternately, trying another browser on the iPad?

**Comment by ThomasJorna** [comment] 2020-12-15 17:29
I've had the same issue, but only occasionally. I was just writing up a bug report about this, but there seems to be a problem with the page content loading correctly on Google Chrome, on of our visitors alerted us of this.

![image](https://user-images.githubusercontent.com/21983833/102249956-3a453d00-3f03-11eb-85aa-64e727516c3c.png)

Disabling the cache and reloading _usually_ fixes it, but not always. After a couple of reloads I'm also not able to reproduce the problem anymore, even after closing the browser. It also didn't seem to be the case that something did not load correctly (no 404s in the network log)

It seems to be a Chrome specific problem, as apparently Edge and Brave don't seem to display the issue.

**Comment by gabestein** [comment] 2020-12-15 17:35
Thanks for this, Thomas. We've seen it sporadically this week in a few browsers, including Edge, so we don't think it's Chrome specific – more likely a cache issue on our end. But we're trying to track it down. If you see it again, could you try to open the console, visit the network tab, and send us the request headers for the main.*.css and main.*.js bundles?

**Comment by ThomasJorna** [comment] 2020-12-15 17:37
Will do!

**Comment by mollygloom** [comment] 2020-12-15 19:13
Hi—

yes, the display issue looks like Thomas’s screen shot, and does not clear up with multiple reloads on either Safari or Chrome for me on iPad, with the addition of being signed into PubPub and not being able to sign into SAR (claims invalid email and will allow me to log in even as a user, let alone admin)

![563182DF-887A-4BE9-BD1F-863BFFCE003F](https://user-images.githubusercontent.com/74009373/102261487-a6c33a80-3f09-11eb-99cb-0a6e31fa9840.png)
![34A51673-FCB9-49DF-9078-59B000B71BCD](https://user-images.githubusercontent.com/74009373/102261492-a7f46780-3f09-11eb-956a-3e88df944f05.png)

**Comment by mollygloom** [comment] 2020-12-16 08:07
Right, the display issue has gone this morning, but I remain unable to log into SAR — while being logged in globally to PubPub and may edit my own ‘community’. I keep receiving an error of ‘invalid email or password,’ as in the first screen shot above.

**Closed** 2020-12-16 08:40 UTC
Labels: bug

**Comment by gabestein** [comment] 2020-12-16 15:46
Thanks Molly, and sorry about those issues. Glad to hear the password reset worked out. We did some work on the display issue yesterday, although we're still not 100% sure what's going on, so do re-open this if you see it again.
