### ISSUE TITLE
Default JODS layout too small on OS X/Chrome

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#330] opened 2019-04-14 20:25 UTC
[http://jods.mitpress.mit.edu](http://jods.mitpress.mit.edu) defaults to a mobile layout on Chrome 73 on Mac OS High Sierra & El Capitan.
This is probably not intended, and too small to be legible.

**Comment by metasj** [comment] 2019-04-14 21:15
<img width="1051" alt="jods-mobile-bug" src="https://user-images.githubusercontent.com/1615548/56099288-d6ba6f00-5ed8-11e9-840b-2d1ca3b6a2fa.png">

**Comment by gabestein** [comment] 2019-07-08 13:48
Is this still an issue? We've been unable to reproduce, and I think we chatted in-person about it potentially being a zoom issue.

**Comment by isTravis** [comment] 2019-07-08 13:55
It is not. We found it was a local browser zoom-setting issue. Apologies for not closing sooner.

**Closed by isTravis** 2019-07-08 13:55 UTC
Labels: design, enhancement
