### ISSUE TITLE
Contributor Title is in Citation

### ISSUE THREAD

**Issue by amdeis** [pubpub/pubpub#3043] opened 2024-03-14 21:02 UTC
### What went wrong, step-by-step?

1. Linked contributor to byline of pub
2. contributor included a "title" in their PubPub profile (in this case, PhD)
3. Contributor title is included with their name in byline (screenshot included), which isn't standard for journals so we can't use at HDSR and might have to stop linking authors that use the "title" feature in PubPub or ask them to blank that section of their profile, but more importantly...
4. Contributor title is included in citation (screenshot)

### What did you expect to happen?

Citation would include only author names, not name and title. 
(Maybe also make showing their title on the byline of a pub/article optional?)

### What URL can we use to see the issue?

https://hdsr.mitpress.mit.edu/pub/6blzwgpg/draft?readingCollection=a6db7dff currently, but I've asked the author to blank the "title" in their profile so we can publish the issue, so might not be relevant anymore.

### What browser/operating system were you using?

Firefox. Windows 11.

### Have any screenshots? (Attach them by dragging the image here)

![Screenshot 2024-03-14 at 16-54-23 An Invisible Hand for Creating Public Value From Data](https://github.com/pubpub/pubpub/assets/117661410/09d5fb3a-dbc6-4f76-91d7-9a6b9a1cc0d6)
![Screenshot 2024-03-14 at 16-54-34 An Invisible Hand for Creating Public Value From Data](https://github.com/pubpub/pubpub/assets/117661410/fd5fff14-f9a4-4e7b-946a-190d49fc2e47)
![Spector profile (Dr ) title](https://github.com/pubpub/pubpub/assets/117661410/eb04a9d3-1159-4a56-8607-246727181034)

### Who reported this? (If not you)
Amara Deis (HDSR)

**Comment by gabestein** [comment] 2024-03-15 14:27
Huh, weird. We can fix this pretty quickly so you don't need to mess with folks' bios.

**Comment by amdeis** [comment] 2024-03-18 18:09
I made a mistake. I included screenshot of author Alfred Spector’s (https://hdsr.mitpress.mit.edu/user/alfred-spector) account in that GitHub as the problem, but he is NOT the one showing “Ph.D” in the byline of the article (https://hdsr.mitpress.mit.edu/pub/6blzwgpg/draft?access=fbhhwq8l). Author **Michael Stebbins's** (https://hdsr.mitpress.mit.edu/user/michael-stebbins) account is the one showing “Michael Stebbins, Ph.D.” in the byline. 

1.	I cannot see the details of Stebbin’s account—could you tell me where his name went wrong? (maybe his “Ph.D” is in his name section instead of “title” the way Spector has it?)
2.	Does the author need to implement a fix, or is this from PubPub’s side?

**Comment by gabestein** [comment] 2024-03-18 19:00
Thanks for following up. Yes, indeed the issue is that Michael's last name gield includes "Ph.D". He'll need to correct that for the citation to function properly. I'm closing out the issue since it's not on our end.

**Closed by gabestein** 2024-03-18 19:00 UTC
Labels: bug
