### ISSUE TITLE
Adding links: make it hard to overwrite the text w/ the URL rather than adding a link

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#421] opened 2019-06-15 22:31 UTC
Found many times by SJ, especially on docs w/ multiple shared editors.
Using Win/Chrome or Mac/Chrome.

**Description**
When selecting a piece of text to add a link, after the URL-field is visible, pasting the URL overwrites the text rather than adds it into the URL field.  This happens even after a cursor seems to be visible in the URL field.  The only way I've found to be completely certain of not overwriting the text is to mouse over to the URL field and click on it before pasting.

This is in contrast to the reliable single-editor behavior of focus being immediately captured by the URL field as soon as it appears. 

**Plain-language description**
After selecting text to add a URL, and clicking on the 'add link' icon, pasting in a URL often overwrites the text rather than adding the desired link.

**Steps to reproduce**
Start a collaborative editing session with at least three people editing the same, reasonably long, document.  Try adding links to words until this occurs.

**Comment by metasj** [comment] 2019-06-15 22:32
This most recently happened to me when editing a doc that was >100kb and had ~5 people reading it (if not actively editing) at the time.

**Comment by gabestein** [comment] 2019-08-05 21:20
We're pretty confident this was addressed in a bug relating to the link popover not opening, and I have been unable to reproduce since then. Please re-open if this recurs.

**Closed by gabestein** 2019-08-05 21:20 UTC
Labels: bug
