### ISSUE TITLE
Banner block overlay

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#979] opened 2020-08-10 23:03 UTC
_Before filing your enhancement, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

**What's your enhancement request?**
Can we make this optional or changeable like in the pub banners?

**What would this enhancement help you accomplish?**
would make this into a space for better community branding and add nice design flexibility

---

**Any attachments or reference images? (Drag them here)**

**What's the URL to your PubPub community?**

**Who requested this? (If not you)***
Me!

**Comment by idreyn** [comment] 2020-08-13 15:46
Closing as a duplicate of #978 (which is on our radar!)

**Closed by idreyn** 2020-08-13 15:46 UTC
Labels: enhancement
