### ISSUE TITLE
Custom Citation and Counting

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#1544] opened 2021-08-20 14:14 UTC
Enhancement requests are requests to make changes to an existing PubPub feature. If you'd like to suggest a new feature, please post in the ideas section of our [https://github.com/pubpub/pubpub/discussions](discussion forum).

_Before filing your enhancement, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the request, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What's your enhancement request?
When using the custom citation option for citations in pubs, the pub counts each citation as an additional, new citation even when it's identical, aside from how you choose for it to appear within the text. It's hard to explain. See this video: https://recordit.co/7orDcR2QwU

Each of those references are the same, but have a different appearance in-line and are this counted as a new reference in the list at the bottom of the pub 

### What would this enhancement help you accomplish?
less duplication
---

### Any attachments or reference images? (Drag them here)
https://recordit.co/7orDcR2QwU

### What's the URL to your PubPub community?
https://commonplace.knowledgefutures.org/pub/fxpbh1q2/draft

**Comment by gabestein** [comment] 2021-08-31 16:13
We took a look today. Unfortunately, I'm not sure if this is solvable, so I'm going to close it for now.

I believe the issue isn't with custom labels, it's that the citation is rich text, rather than structured, so we have no way to compare them to each other other than trying to make a string comparison, which would be fraught and unsatisfying. I believe that if the references were switched to a structured form like bibtex (with an ID) or DOI, we would deduplicate the bibliography with or without custom labels. And if we don't currently, that is something we could likely support.

We also discussed the need, somewhere down the line, to move to more of a robust citation management system where you can link citation nodes to a global citation database and make changes upstream that would be reflected downstream. But that's a ways off.

**Closed by gabestein** 2021-08-31 16:13 UTC
Labels: bug
