### ISSUE TITLE
Pub description

### ISSUE THREAD

**Issue by coahearn** [pubpub/pubpub#974] opened 2020-08-07 19:17 UTC
**What's your enhancement request?**
Right now if you paste in a description that's over 280 characters and hit enter, the full description disappears. Recommend cutting off any pasted bit of text at 280.

**What would this enhancement help you accomplish?**
Better user experience; no risk of losing work.

---

**Any attachments or reference images? (Drag them here)**
https://recordit.co/bf7kWe7iwg

**What's the URL to your PubPub community?**

**Who requested this? (If not you)***
RRC19, and me

**Comment by gabestein** [comment] 2020-08-07 19:33
Duplicate of #971

**Closed by gabestein** 2020-08-07 19:33 UTC
Labels: enhancement
