### ISSUE TITLE
Can't comment on text in a table

### ISSUE THREAD

**Issue by avanouse** [pubpub/pubpub#1458] opened 2021-06-03 13:36 UTC
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. I tried to post discussion on text within a table.
2. Text highlights as it should when the comment field appears, but no box pops up for my comment.
...

### What did you expect to happen?
Comment box as usual!

### What URL can we use to see the issue?
https://help.pubpub.org/pub/t93cdkpt/draft/202?from=4250&to=4298

### What browser/operating system were you using?
Safari, Chrome and Firefox.

===

### Have any screenshots? (Attach them by dragging the image here)
<img width="1063" alt="Screen Shot 2021-06-03 at 9 47 24 AM" src="https://user-images.githubusercontent.com/60357197/120655542-c6670480-c450-11eb-8517-7b042091b638.png">

Please advise to send screen recording, if this doesn't reflect what happens for you!

**Comment by gabestein** [comment] 2021-06-03 14:05
Thanks! Marking as a duplicate of #571. We'll get to it.

**Closed by gabestein** 2021-06-03 14:05 UTC
Labels: bug
