### ISSUE TITLE
Changing Collection Title

### ISSUE THREAD

**Issue by sarah-tonin** [pubpub/pubpub#1579] opened 2021-10-01 14:21 UTC
_Before filing your bug report, please search existing issues to make sure a similar one doesn't already exist. If one does, please leave a comment or reaction in support of the issue rather than creating a new one._

_To fill out the report, please leave the below headers (**) in tact, and fill out each section. If a section isn't applicable, leave it blank or write n/a under it. Please do not delete any template sections._

### What went wrong, step-by-step?
1. When I go to a collection's settings
2. I try and change the collection title and the link slug
3. I smash that save button
4. But the collection title (not the url) reverts back to what it was
5. A re-fresh doesn't change this 
...

### What did you expect to happen?
I wanted the collection title to change. 

### What URL can we use to see the issue?
https://commonplace.knowledgefutures.org/dash/collection/global-transition-to-open/settings

### What browser/operating system were you using?
MacOS / Chrome

===

**Comment by gabestein** [comment] 2021-10-01 14:25
Yeah, this is bad UX we're aware of and need to fix. You can see more discussion and the workaround here: https://github.com/pubpub/pubpub/discussions/1413

(Duplicate of #1255)

**Closed by gabestein** 2021-10-01 14:25 UTC
Labels: bug
