### ISSUE TITLE
Hover tooltip for Pub's primary collection blinks/flashes rapidly

### ISSUE THREAD

**Issue by cfcohen** [pubpub/pubpub#1511] opened 2021-07-24 18:19 UTC
### What went wrong, step-by-step?
1. Visit the dashboard page for a collection of publications.
2. Hover over the star icon.
3. The hover tooltip text "This Pub's Primary Collection" flashes rapidly.
4. The icon does not appear to be clickable as a result.
...

### What did you expect to happen?

For the hover tooltip to remaining open and open slightly away from the icon.

### What URL can we use to see the issue?

https://medieval.pubpub.org/dash/collection/six-centuries-of-work-and-wages/overview

### What browser/operating system were you using?

Firefox 90.0 64-linux for Ubuntu

### Have any screenshots? (Attach them by dragging the image here)

I do not have screenshots.

### Who reported this? (If not you)

Reported by me.

**Comment by gabestein** [comment] 2021-08-31 16:08
Thanks for reporting this! We're unable to reproduce it on Firefox latest, so we're closing it for now. Feel free to re-open if it persists.

**Closed by gabestein** 2021-08-31 16:08 UTC
Labels: bug
