### ISSUE TITLE
Feature Request: copy editing ability

### ISSUE THREAD

**Issue by devinberg** [pubpub/pubpub#69] opened 2016-05-08 16:57 UTC
I think it might be good for a journal admin or assigned copy editor to have edit permissions on pubs submitted to a particular journal. This would help in situations when authors have formatting troubles or for other normal copy editing tasks sometimes carried out by journals.

**Comment by isTravis** [comment] 2016-05-10 13:41
For sure. We need some copy-editing role in the system somehow. I'm not sure if making the Journal editor have 'edit' access is totally sound. Perhaps the author wants to be able to review these changes first. It's a larger design decision I think, which I post in #70. 

Would love your feedback there.

**Comment by devinberg** [comment] 2016-05-17 20:03
I'm not really sure of the exact mechanism. Perhaps a "type" of comment
that is a revision suggestion. Author accepts or declines and that is noted
within the discussion area.

**Comment by gabestein** [comment] 2019-01-10 02:39
Duplicate of #70

**Closed by gabestein** 2019-01-10 02:39 UTC

**Comment by gabestein** [comment] 2019-01-10 02:50
_We're moving non-code discussion of features and bugs to [Discourse](https://discourse.knowledgefutures.org). This issue has been re-opened and updated [here](https://discourse.knowledgefutures.org/t/track-changes-suggestions-and-copyediting-modes/19)_
