### ISSUE TITLE
Citation upgrades

### ISSUE THREAD

**Issue by ThomasJorna** [pubpub/pubpub#1067] opened 2020-09-30 20:04 UTC
**What's your enhancement request?**
Two things:
-Sort citations by author last name instead of by appearance. 
-Set multiple "standard" inline citation styles, e.g. (With Brackets, 2020) and Without Brackets (2020)

**What would this enhancement help you accomplish?**

Our journal uses APA-style for references, which requires alphabetically sorted bibliographies. I quite like PubPub's built in citation system as it gives you a pop-up showing you the full citation on hover, but we cannot use it at the moments since the bibliography/citations aren't formatted correctly. 
The second issue could be fixed manually, but that makes adding citations an even bigger hassle. One make this easier could be to have the selected text be automatically used as the custom citation input. This would be especially useful to us, as most of our authors prefer not to write their article in PubPub.

---

**Any attachments or reference images? (Drag them here)**
![image](https://user-images.githubusercontent.com/21983833/94733636-5d326d00-0368-11eb-8bee-9f3792ac407b.png)
Ideally I could have it look like this in the citations list.

Suggestion for citation quality of life changes:
![image](https://user-images.githubusercontent.com/21983833/94733857-b1d5e800-0368-11eb-99a5-70089558b59b.png)
![image](https://user-images.githubusercontent.com/21983833/94733945-cade9900-0368-11eb-9465-6db56713dbed.png)

**What's the URL to your PubPub community?**
https://jtrialerror.pubpub.org
**Who requested this? (If not you)***

**Comment by ThomasJorna** [comment] 2020-10-02 14:00
A further illustration of the specific interaction I'm looking for:

This is how PubPub interprets LaTeX's \textcite{Collins1972, Collins etc...}, which "should" be rendered as Collins (1972, 19...) but instead is interpreted as \parencite{Collins1972}\parencite{Collins...} and thus rendered as 4 separate citations, rendering it pretty much unusable for more than 1 citation.
![image](https://user-images.githubusercontent.com/21983833/94931167-b95fd300-04c7-11eb-9dee-e68a89bff192.png)

On a positive note: it's fantastic that PubPub is able to convert a tex and bib file to such nice citations so seemlessly, everything is accounted for!

**Comment by gabestein** [comment] 2020-10-02 14:13
Thanks, Thomas. I suspect you've seen this given your proposed solutions, but as a workaround for now, even though it can be time-consuming, you can use the custom citation text feature to strip out the extra parens.

We'll take a look at various solutions. I think the with/without parens idea could be good, but we're a little concerned about the potential explosion of different styles since there are so many ones folks use, depending on the discipline. And that wouldn't solve the problem of still needing parens around the entire block of citations, although it would certainly reduce the work required.

As you've discovered, there is some incompatibility between how LaTeX handles citations and how PubPub does – but it's not exactly as you're describing. It's not that PubPub interprets `\textcite` as `\parencite`, it's that all citations are interpreted as individual entities by PubPub and then rendered as such – we have no equivalent concept to \textcite. So, I'm not exactly sure what our approach should be. With JATS, we're able to get around this by using the contents of `<xref>...</xref>` as the custom citation text if it exists. Usually, in a JATS citation block, the parens are plaintext, ie `(<xref>Collins, 1974</xref>; <xref>Collins, 1992</xref>;...)`, so we render it properly.

But because LaTeX generates that content during the render step, I'm not sure what we get via Pandoc – I'll investigate, but if, as I suspect, it just gives us raw bibtex, it means there's likely no complete short-term solution for these edge cases, because we'll have to write something custom to handle `\textcite`, which likely won't get prioritized for a bit.

Hope that's helpful, and if you have any other suggestions given that context, please let me know!

**Comment by ThomasJorna** [comment] 2020-10-04 11:00
Thanks for the in-depth explanation Gabe! Interesting to know how this is handled on the backend, I will experiment around a bit more to see what is possible. As I said, I really like the idea of the cite system, it's very interactive and saves a lot of scrolling back and forth.

The only big request I would have would be alphabetic citation ordering. The \parencite/ \textcite thing I could work around, but we can't use it in its current form without that sorting ability. I do see that that might not be trivial to implement from poking around the implementation a bit, just from looking at the components I couldn't really figure out a good way to do it myself. 

In any case, I'll be looking forward to further developments on this front, keep up the good work!

**Comment by gabestein** [comment] 2021-03-19 20:30
Partial dupe of #928. I see no reason to switch to alpha vs. our current cite-order, given the universality of alphabetic lists. Potentially a good candidate @howebenhowe in a bit, as it involves editor, settings, pub footer, and downloads.

**Closed** 2021-04-20 15:09 UTC
Labels: enhancement
