### ISSUE TITLE
Easier cross-pub linking

### ISSUE THREAD

**Issue by metasj** [pubpub/pubpub#646] opened 2019-12-12 16:01 UTC
As an editor, I often want to link to other pubs in the same community. 

- I'd like an inline way to do this, if not an option in the toolbar.  E.g. {pub name}.
- I'd also like a way to see, inline, whether the target of an internal link exists or not (without having to try opening it in a new tab).  
- I'd like an interface for this that tries to autofill the name of the internal pub, to help me choose the target I want.  

This will help improve link density, incentivize choosing memorable names for pubs, and improve reuse of pubs over time.

**Comment by gabestein** [comment] 2019-12-12 16:05
Thanks! Agreed. 

Closing as a duplicate of #630 :)

**Closed by gabestein** 2019-12-12 16:05 UTC
Labels: feature request
